import json
import logging
from datetime import datetime

from dateutil.relativedelta import relativedelta

from odoo import api, fields, models, _, exceptions
from odoo.exceptions import UserError

from . import prompts

_logger = logging.getLogger(__name__)


class ProjectTask(models.Model):
    _inherit = "project.task"

    x_linked_lead_id = fields.Many2one(
        "crm.lead",
        string="Linked Lead",
        help="Primary CRM lead associated with this presale ticket.",
    )
    x_wbs_sheet_url = fields.Char(
        string="WBS Sheet URL",
        help="Google Sheets URL generated by n8n for this ticket's WBS.",
    )
    x_proposal_drive_url = fields.Char(
        string="Proposal Drive URL",
        help="Google Drive URL of the generated proposal document.",
    )
    x_ticket_status = fields.Selection(
        [
            ("open", "Open"),
            ("ready_for_wbs", "Ready for WBS"),
            ("wbs_done", "WBS Done"),
            ("ready_for_proposal", "Ready for Proposal"),
            ("proposal_generated", "Proposal Generated"),
            ("proposal_sent", "Proposal Sent"),
            ("closed", "Closed"),
        ],
        string="Presale Status",
        default="open",
        tracking=True,
    )
    x_last_agenda_date = fields.Date("Last Agenda Date")
    x_retro_logged = fields.Boolean("Retro Logged")

    def _claude(self):
        return self.env["claude.service"]

    # -------------------------------------------------------------------------
    # Ticket creation gist (Phase 10)
    # -------------------------------------------------------------------------

    @api.model
    def create(self, vals):
        task = super().create(vals)
        if task.x_linked_lead_id:
            try:
                task.action_generate_ticket_gist()
                task.x_linked_lead_id.x_presale_ticket_id = task
            except Exception:
                _logger.error("Failed generating ticket gist for task %s", task.id, exc_info=True)
        return task

    def action_generate_ticket_gist(self):
        """Summarize all prior discussions from the linked lead for presale."""
        for task in self.filtered("x_linked_lead_id"):
            lead = task.x_linked_lead_id
            # Last 50 messages
            msgs = lead.message_ids.sorted("date", reverse=False)[-50:]
            lines = []
            for m in msgs:
                if m.message_type not in ("email", "comment"):
                    continue
                snippet = (m.body or "").replace("\n", " ")
                lines.append(
                    f"[{m.date}] {m.author_id.display_name or ''}: {snippet[:400]}"
                )
            if not lines:
                task.message_post(
                    body=_("No prior discussions found on the lead. Ticket ready for presale input."),
                    subtype_xmlid="mail.mt_note",
                )
                continue

            try:
                summary = self._claude().call(
                    tier="sonnet",
                    system_prompt=prompts.PROMPTS["ticket_gist_system"],
                    user_message="\n\n".join(lines)[:120000],
                    max_tokens=1500,
                    expect_json=False,
                )
            except Exception:
                _logger.error("Ticket gist generation failed for task %s", task.id, exc_info=True)
                continue

            task.message_post(
                body=summary or _("Presale ticket created with summarized history."),
                subtype_xmlid="mail.mt_note",
            )

    # -------------------------------------------------------------------------
    # Daily presale agenda (Phase 11)
    # -------------------------------------------------------------------------

    @api.model
    def cron_generate_presale_agenda(self):
        """
        10:30 AM cron – per-ticket daily agenda.
        """
        today = fields.Date.today()
        tickets = self.search(
            [
                ("x_ticket_status", "in", ["open", "ready_for_wbs", "wbs_done"]),
            ]
        )
        for task in tickets:
            try:
                task._generate_single_agenda(today)
            except Exception:
                _logger.error("Agenda generation failed for task %s", task.id, exc_info=True)

    def _generate_single_agenda(self, today):
        self.ensure_one()
        since = self.x_last_agenda_date or (today - relativedelta(days=2))
        msgs = self.message_ids.filtered(
            lambda m: m.date and m.date.date() >= since
        ).sorted("date", reverse=False)
        lead_msgs = self.x_linked_lead_id.message_ids if self.x_linked_lead_id else self.env[
            "mail.message"
        ]
        lead_recent = lead_msgs.filtered(
            lambda m: m.date and m.date.date() >= since
        ).sorted("date", reverse=False)

        lines = ["[Ticket Activity]"]
        for m in msgs:
            lines.append(f"[{m.date}] {m.author_id.display_name}: {(m.body or '')[:400]}")

        lines.append("\n[Lead Activity]")
        for m in lead_recent:
            lines.append(f"[{m.date}] {m.author_id.display_name}: {(m.body or '')[:400]}")

        try:
            agenda_html = self._claude().call(
                tier="haiku",
                system_prompt=prompts.PROMPTS["presale_agenda_system"],
                user_message="\n".join(lines)[:160000],
                max_tokens=800,
                expect_json=False,
            )
        except Exception:
            _logger.error("Agenda Claude call failed for task %s", self.id, exc_info=True)
            return

        if agenda_html:
            self.message_post(body=agenda_html, subtype_xmlid="mail.mt_note")
            self.x_last_agenda_date = today

    # -------------------------------------------------------------------------
    # Presale email drafter (Phase 12)
    # -------------------------------------------------------------------------

    def action_generate_presale_client_email(self, mom_content=None):
        self.ensure_one()
        lead = self.x_linked_lead_id
        if not lead:
            return

        # Last 10 client conversations
        history_msgs = lead.message_ids.sorted("date", reverse=False)[-20:]
        history = []
        for m in history_msgs:
            if m.message_type == "email":
                history.append(
                    f"[{m.date}] {m.author_id.display_name}: {m.subject or ''} :: {(m.body or '')[:400]}"
                )

        if mom_content is None:
            # Use last few notes from ticket
            ticket_notes = self.message_ids.filtered(
                lambda m: m.subtype_id.xml_id == "mail.mt_note"
            ).sorted("date", reverse=False)[-5:]
            mom_content = "\n\n".join((n.body or "")[:800] for n in ticket_notes)

        user_msg = json.dumps(
            {
                "presale_mom": mom_content,
                "client_history": history,
            },
            ensure_ascii=False,
        )

        try:
            resp = self._claude().call(
                tier="sonnet",
                system_prompt=prompts.PROMPTS["presale_email_system"],
                user_message=user_msg,
                max_tokens=800,
                expect_json=True,
            )
        except Exception:
            _logger.error(
                "Presale email draft failed for task %s / lead %s",
                self.id,
                lead.id,
                exc_info=True,
            )
            return

        subject = resp.get("subject") or _("Follow-up from our technical discussion")
        body_html = resp.get("body_html") or _(
            "<p>Following up on our recent technical discussion.</p>"
        )

        activity_type = self.env.ref(
            "sales_ai_integration.activity_type_presale_email", raise_if_not_found=False
        )
        self.env["mail.activity"].sudo().create(
            {
                "res_model": "crm.lead",
                "res_id": lead.id,
                "user_id": lead.user_id.id,
                "activity_type_id": activity_type.id if activity_type else False,
                "note": "[AI DRAFT — Presale]\n\n" + subject + "\n\n" + body_html,
                "date_deadline": fields.Date.today(),
            }
        )

    # -------------------------------------------------------------------------
    # Request Proposal from AI (Phase 13)
    # -------------------------------------------------------------------------

    def action_request_proposal_from_ai(self):
        self.ensure_one()
        if self.x_ticket_status != "wbs_done":
            raise UserError(_("Complete WBS validation before requesting a proposal."))
        if not self.x_wbs_sheet_url:
            raise UserError(_("WBS Google Sheet URL is missing."))
        if not self.x_linked_lead_id:
            raise UserError(_("This ticket is not linked to a sales lead."))

        self.x_ticket_status = "ready_for_proposal"

        n8n = self.env["sales.ai.n8n"]
        payload = {
            "ticket_id": self.id,
            "ticket_name": self.name,
            "ticket_description": self.description or "",
            "lead_id": self.x_linked_lead_id.id,
            "wbs_sheet_url": self.x_wbs_sheet_url,
        }
        n8n.post("proposal_request", payload)

        return {
            "type": "ir.actions.client",
            "tag": "display_notification",
            "params": {
                "title": _("Proposal Requested"),
                "type": "success",
                "message": _(
                    "AI proposal generation triggered. Google Drive link will appear on the ticket."
                ),
            },
        }

